### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by c3c1l1a** [mirwaisfarahi/Todo-List#8]
# Highlights
- The code is well structured and uses [classes](https://github.com/mirwaisfarahi/Todo-List/blob/0139f9f5eea9a2dc78ce415952d5950fbafa6b0c/src/storage.js#L1) to abstract out functionality. 
- The code follows the DRY principle
- The code uses brief comments so it's easy to understand it

**Comment by mirwaisfarahi** [comment]
Thank you for your nice comments about the project.
